/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.casino;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author mor
 */
public class mainWindow extends javax.swing.JFrame {
    HiLoWin hiloWin;
    BlackJackWindow bjWin;
    SlotMachine sm;
    balancePalet bp;
    int dollarAmount;
    Player player;
    LoginWindow logw;
    /**
     * Creates new form mainWindow
     */
    
    public mainWindow(Player a, LoginWindow logw) {
        initComponents();
        player = a;
        bp.wallet = player.getBalance();
        balancePalet1.updateBalance();
        this.logw = logw;
        logw.setVisible(false);
        hiloWin = new HiLoWin(player, this);
        sm = new SlotMachine(player, this);
        bjWin = new BlackJackWindow(player, this);
        hiloWin.setVisible(false);
        sm.setVisible(false);
        bjWin.setVisible(false);
        
        
        
    }
    
    public void setNewPlayer(Player a){
        player = a;
        bp.wallet = player.getBalance();
        balancePalet1.updateBalance();
    }
    public void setNewWallet(){
        bp.wallet = player.getBalance();
        balancePalet1.updateBalance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        slot = new javax.swing.JButton();
        btnHiLo = new javax.swing.JButton();
        bjBtn = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        balancePalet1 = new com.mycompany.casino.balancePalet();
        btnDeposit = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        slot.setText("Slot Machine");
        slot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slotActionPerformed(evt);
            }
        });

        btnHiLo.setText("HiLo");
        btnHiLo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHiLoActionPerformed(evt);
            }
        });

        bjBtn.setText("BlackJack");
        bjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bjBtnActionPerformed(evt);
            }
        });

        btnWithdraw.setText("Withdraw");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnDeposit.setText("Deposit");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        logoutBtn.setText("Log out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(balancePalet1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeposit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnWithdraw))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bjBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(slot, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHiLo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHiLo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slot, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bjBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnWithdraw)
                        .addComponent(btnDeposit))
                    .addComponent(balancePalet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(logoutBtn)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slotActionPerformed
        // TODO add your handling code here:
        sm.setNewWallet();
        sm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_slotActionPerformed

    private void btnHiLoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHiLoActionPerformed
        // TODO add your handling code here:
        hiloWin.setNewWallet();
        hiloWin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHiLoActionPerformed

    private void bjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bjBtnActionPerformed
        // TODO add your handling code here:
        bjWin.setNewWallet();
        bjWin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bjBtnActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        // TODO add your handling code here:
        dollarAmount = Integer.parseInt(JOptionPane.showInputDialog("Deposit Amount"));
        bp.wallet += dollarAmount;
        balancePalet1.updateBalance();
        player.setWallet(bp.wallet);
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        // TODO add your handling code here:
        if(bp.wallet > 0){
            dollarAmount = Integer.parseInt(JOptionPane.showInputDialog("Withdraw Amount"));
            if(dollarAmount <= bp.wallet){
                bp.wallet -= dollarAmount;
                balancePalet1.updateBalance();
                player.setWallet(bp.wallet);
            }
            else{
                Component frame = null;
                JOptionPane.showMessageDialog(frame,"You dont have this amnount, choose smaller amount.", "Deposit", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else{
            Component frame = null;
            JOptionPane.showMessageDialog(frame,"You dont have money to withdraw.", "Withdraw", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        logw.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.casino.balancePalet balancePalet1;
    private javax.swing.JButton bjBtn;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnHiLo;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton slot;
    // End of variables declaration//GEN-END:variables
}
